apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfstack-api.fullname" . }}-app
  labels:
  {{- include "tfstack-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.type }}
  selector:
    app: tfstack-api-app
  {{- include "tfstack-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.app.ports | toYaml | nindent 2 -}}