apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfstack-api.fullname" . }}-redis
  labels:
  {{- include "tfstack-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
  {{- include "tfstack-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redis.ports | toYaml | nindent 2 -}}